version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: usermgmt_postgres
    environment:
      POSTGRES_DB: user-management-service-task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "9999:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: user_management_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user-management-service-task
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

volumes:
  pgdata:
