server:
  port: 8080

spring:
  application:
    name: User-Management-Service-Task
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    enabled: false  # Prod'da Liquibase CI/CD tarafında çalışacak



# Mail prod’da kapalı (SendGrid vb. eklenecekse burada açarsın)
  mail:
    host:
    port:
    username:
    password:
#logging:
#  level:
#    root: INFO
#    org.springframework.web: WARN
#    org.apache.kafka: INFO
#    org.springframework.web.servlet: WARN
#    org.apache.catalina: WARN
#    org.apache.tomcat: WARN
#    org.hibernate: WARN
#    com.zaxxer.hikari: WARN
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file:
#    name: logs/user-management.log
#  exception-conversion-word: "%xEx{short}"

